### PR TITLE
Add flip coordinates to point pattern

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by sjsrey** [comment]
I think the failures were due to a bug that has now been [fixed](https://github.com/pysal/pysal/pull/756). So updating to pr to see if all other tests pass would be the next step.

**Comment by MridulS** [comment]
@sjsrey Can you restart travis

**Comment by sjsrey** [comment]
@MridulS if you push a commit to your branch, it should fire the tests on travis.

**Comment by MridulS** [comment]
@sjsrey Done :smile:

**Pull request merged**
